services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - NYTIMES_API_KEY=8E7KJlYde0UgO8obuOUwKHPU1sGcCGPx
      - GEMINI_KEY=AIzaSyBHxQgOIRU5Zep1eJNdkrcvic152jEMd8I
      - OPENAI_API_KEY=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
      