name: Pull Request Notifications
on:
  pull_request:
    types: [opened, reopened, synchronize, review_requested, ready_for_review, labeled, unlabeled]
  pull_request_review:
    types:
      - submitted
env:
  requested_reviewers: ${{ toJson(github.event.pull_request.requested_reviewers) }}
  GCHAT_WEBHOOK_URL: https://chat.googleapis.com/v1/spaces/AAAAu0pPs_8/messages?key=AIzaSyDdI0hCZtE6vySjMm-WEfRq3CPzqKqqsHI&token=2OA68qb_Xv29GMQUPkYHIb2Sm3e3AspjdZ7DAaeNQ0A

jobs:
  notify-google-chat:
    runs-on: ubuntu-latest
    steps:
      # Notify when a PR is raised
      - name: Notify Google Chat about PR Raised
        if: github.event.action == 'opened'
        env:
          WEBHOOK_URL: ${{ env.GCHAT_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "🚀 A new pull request has been raised: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}) by ${{ github.event.pull_request.user.login }}"
          }' $WEBHOOK_URL

      # Notify when PR reviews are fulfilled
      - name: Check if all reviews are approved
        if: github.event.action == 'submitted'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo gh api --method GET /repos/siddiqkaithodu/news-summariser/pulls/1/reviews
          APPROVED_COUNT=$(gh api --header 'Accept: application/vnd.github+json' --method GET /repos/{owner}/{repo}/pulls/{pull_number}/reviews state --jq '[.[] | select(.state=="APPROVED")] | length')
          REQUIRED_REVIEWS=$(gh repo view --json pullRequests --jq '.pullRequests.nodes[].reviewRequests.totalCount')
          if [ "$APPROVED_COUNT" -ge "$REQUIRED_REVIEWS" ]; then
            echo "All required reviews are fulfilled. Proceeding to notify Google Chat."
          else
            echo "Not all required reviews are fulfilled yet."
          fi

      - name: Notify Google Chat to Merge Code
        if: github.event.action == 'submitted' && env.APPROVED_COUNT >= env.REQUIRED_REVIEWS
        env:
          WEBHOOK_URL: ${{ env.GCHAT_WEBHOOK_URL }}
        run: |
          curl -X POST -H "Content-Type: application/json" -d '{
            "text": "✅ All reviews required are fulfilled for PR: [${{ github.event.pull_request.title }}](${{ github.event.pull_request.html_url }}). You can merge the code now!"
          }' $WEBHOOK_URL