name: Build and Publish Docker Image

on:
  push:
    # branches: [ "main" ]
    paths:
      - 'Dockerfile'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.sha }}
          github_token: ${{ secrets.GITHUB_TOKEN }}